### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-joanajimfer#1]
Good job @joanajimfer  !!!

Here you have some tips to improve the exercise:

- [x] Remove unused files/folders from the project: assets/icons, assets/images...
- [x] Remove unneeded divs (around 'answer__number' and 'play__number')
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Fix the main title of the page (it's not 'Prueba intermedia 2' but 'Adivina el número',) and add a proper HTML tag for it
- [x] Define the logic to make the counter work
- [x] Don't use a `return` statement in a callback to return a value because it's not possible to get the value in the `addEventListener`
- [x] Do not execute 'showPlayerNumber'! The browser will execute it when the user clicks the button
- [x] Remember to convert input value string to a number
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs

You are close to the exercise solution, but here you are a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by joanajimfer** [comment]
Hello @nasivuela, I correct the issues and now the game works properly, 
please, check it to know if it is ok.

**Comment by nasivuela** [comment]
Awesome @joanajimfer !!

I'm closing this, but here you have more tips if you want to keep improving it:
- if/else do not end with `;`
- You are writing many times `parseInt(writePlayerNumber)`, what about saving that into a constant to reuse it?
- You are writin many times `writtingPlace.innerHTML = 'something';`, what moving it to a function to reuse it?
- Move your constants and variables to the top of the scope.
- What do you think about adding a reset functionality?
- Responsive
- ... and whatever else you want to do ;)

![](https://media.giphy.com/media/xUA7baWfTjfHGLZc3e/giphy.gif)
